import pika
import json
import time
import random

# 1. Connect to RabbitMQ container (running in Docker)
connection = pika.BlockingConnection(pika.ConnectionParameters('127.0.0.1'))
channel = connection.channel()

# 2. Create a 'Queue' (a holding pen for messages)
channel.queue_declare(queue='log_queue')

print("--- Producer started. Sending logs to RabbitMQ... (Press Ctrl+C to stop.) ---")

levels = ["INFO", "WARNING", "ERROR"]
services = ["auth-service", "payment-service", "ui-gateway"]

try:
    while True:
        # 3. Create a structured log entry in a dictionary
        log_entry = {
            "timestamp": time.strftime("%d-%m-%Y %H:%M:%S"),
            "level": random.choice(levels),
            "service": random.choice(services),
            "message": "Simulated log message generated by producer"
        }
        # 4. Convert the dictionary to a JSON string
        message = json.dumps(log_entry)

        # 5. Send the message to the queue
        channel.basic_publish(exchange='',
                              routing_key='log_queue',
                              body=message)
        
        print(f" [x] Sent: {message}")

        # Wait for a period before sending the next log
        time.sleep(random.uniform(1, 3))

except KeyboardInterrupt:
    print("\nStopping producer...")
    connection.close()